spring.application.name=services
# CONFIGURACIÓN DE BASE DE DATOS (ORACLE CLOUD)
spring.datasource.url=jdbc:oracle:thin:@nextsong_high?TNS_ADMIN=C:/Users/hinat/Downloads/Nextsong-Web/services/Wallet_NextSong
spring.datasource.username=ADMIN
spring.datasource.password=NextSong1234*
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# CONFIGURACIÓN JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
# CONFIGURACIÓN DE CORREO (GMAIL)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=marioloku35@gmail.com
spring.mail.password=uywmnjiqioenoeku
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# HAPPI.DEV API KEY
happi.api.key=hk925-fROXPfrPyIPknfmRF7xId8LT1NC3hCCSYp
# LAST.FM API KEY (dejar vacío si no tienes, el servicio se desactiva solo)
lastfm.api.key=07f6f007b145446607a53308f2021e0d
