spring.application.name=services

spring.datasource.url=jdbc:oracle:thin:@nextsong_high?TNS_ADMIN=C:/Users/LENOVO/OneDrive/Escritorio/Nextsong-Web/services/Wallet_NextSong
spring.datasource.username=ADMIN
spring.datasource.password=NextSong1234*
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true